server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: ms-transfer-postgres
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/transfers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 30000
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    com:
      example:
        infrastructure:
          feign: DEBUG