server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: ms-teachers-management
  datasource:
    url: jdbc:postgresql://localhost:5432/colaborators
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      teachers: ms.teachers.topic

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    com:
      example:
        infrastructure:
          feign: DEBUG
