version: '3.8'

services:
  zookeeper_project2:
    image: confluentinc/cp-zookeeper:7.2.2
    container_name: zookeeper_project2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data-project2:/var/lib/zookeeper/data
      - zookeeper-log-project2:/var/lib/zookeeper/log

  kafka_project2:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka_project2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_project2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data-project2:/var/lib/kafka/data
    depends_on:
      - zookeeper_project2

  mongo_project2:
    image: mongo:latest
    container_name: mongo_project2
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-project2:/data/db

  mongo-express_project2:
    image: mongo-express:latest
    container_name: mongo-express_project2
    restart: always
    ports:
      - "8084:8083"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_project2
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    depends_on:
      - mongo_project2
  
  postgres_project2: 
    image: postgres:latest
    container_name: postgres_project2
    environment:
      POSTGRES_DB: CSOR
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-project2:/var/lib/postgresql/data

volumes:
  kafka-data-project2:
  zookeeper-data-project2:
  zookeeper-log-project2:
  mongo-data-project2:
  postgres-data-project2:

networks:
  default:
    driver: bridge
