server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: ms-transfer-mongo
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/transfers
      database: transfers
  repositories:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: ms-transfer-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.transfers.kafka.contracts.DriverDto
        spring.json.trusted.packages: com.transfers.kafka.contracts
      auto-offset-reset: earliest
    topic:
      transfer: transfer-topic

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    com:
      example:
        infrastructure:
          feign: DEBUG
