server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ms-bff
  data:
    mongodb:
      uri: mongodb://localhost:27017/persons
      database: persons
  repositories:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ms-person-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.person.kafka.contracts.Event
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: com.person.kafka.contracts
    topic:
      person: person

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    com:
      example:
        infrastructure:
          feign: DEBUG
