server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ms-bff
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/transfers
      database: transfers
  repositories:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9093
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.transfers.kafka.contracts.DriverDto
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: com.transfers.kafka.contracts
    topic:
      transfer: transfer-topic

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    com:
      example:
        infrastructure:
          feign: DEBUG
